// Generated by psil compiler

#ifndef Main_H
#define Main_H

#include "purescript.h"

namespace Main {

using namespace purescript;

auto MainMenuStateAnimating() -> const boxed&;
auto MainMenuStateWaiting() -> const boxed&;
auto MainMenuStateCleanUp() -> const boxed&;
auto MainMenuStateDone() -> const boxed&;
auto LevelStateIntro() -> const boxed&;
auto LevelStatePlaying() -> const boxed&;
auto LevelStateFailure() -> const boxed&;
auto LevelStateSuccess() -> const boxed&;
auto LevelStateCleanUp() -> const boxed&;
auto LevelStateDone() -> const boxed&;
auto MainMenu() -> const boxed&;
auto Level() -> const boxed&;
auto Ending() -> const boxed&;
auto getAssetsPath() -> boxed;
auto main() -> boxed;

} // end namespace Main

#endif // Main_H

